### ISSUE TITLE
Do you see value in a Ref-Monad like State?

### ISSUE THREAD

**Issue by rubenmoor** [purescript/purescript-refs#32]
I am using purescript for a canvas-based web app and don't need any fancy UI library. I end up with a lean, global application state and deal with events quite bare-footed.

I find myself writing

    app <- read refAppState
    flip write refAppState $
        app { foo = newFoo
            , bar = app.bar + 1
            }

quite a lot.

If you don't object, I'll come up with a pull request soon to allow to write the above via a monad for effectfull, global state:

    foo .= newFoo
    bar += 1

I miss the lenses :)

Also, maybe you have a suggestion for the module name.

How about `Effect.Ref.Monad`? Alternatively `Control.Monad.State.Global`.

**Comment by hdgarrood** [comment]
I think something along these lines is unlikely to be merged in this library; we prefer to keep core libraries as lean and unopinionated as is reasonably possible. Are you imagining something that is more or less equivalent to `newtype RefM s m a = RefM (StateT (Ref s) m a)`? Because I don't think that needs to exist; why not just use StateT directly?

**Comment by rubenmoor** [comment]
Putting a reference into a local state (`StateT (Ref s) m a` or `State (Ref s) a`) doesn't make sense. What you mean is probably `ReaderT (Ref s) m a` or `Reader s a`. That still would imply explicit use of `write` and `read` from `Effect.Ref` and does not allow anything close to the syntax above. Correct me if I'm wrong.

**Comment by hdgarrood** [comment]
Yes, you're right, I did mean Reader rather than State. But in any case I don't think this is something we will want to include in this library.

**Comment by rubenmoor** [comment]
My initial idea is complicated by the fact that a reference-based, global state monad, being effectful, cannot have an instance of the type-class `MonadState`, which is of course pure.

The only way out that I can see would be a to re-implement an effectful variant of `MonadState`. This, in turn, implies a re-implementation of all related lenses. A huge copy-and-paste, might still be somewhat useful, but by no means elegant.
