### ISSUE TITLE
Eq instance?

### ISSUE THREAD

**Issue by jbrownson** [purescript/purescript-refs#5]
I think it wouldn't be hard to do an Eq instance for Ref right? Would you be open to a pull request?

**Comment by paf31** [comment]
I think such an instance would be necessarily unsafe. Depending on what sort of equality you want, maybe something like `refEq :: forall a eff. (Eq a) => Ref a -> Ref a -> Eff (ref :: REF | eff) Boolean` would work?

**Comment by jbrownson** [comment]
Ahh, I wasn't clear. I mean reference equality, not dispatching to equality of the contained item.

**Comment by jbrownson** [comment]
It turns out I don't think I'll need it for what I'm doing, but I still think it could be useful and would be happy to do the typing.

**Comment by paf31** [comment]
Perhaps it could go into `Unsafe` as a function then?

```refEq :: forall a. (Eq a) => Ref a -> Ref a -> Eff Boolean```

**Comment by jbrownson** [comment]
I'm not clear on what's unsafe about it? Do I misunderstand javascript's reference equality semantics?

**Comment by jbrownson** [comment]
And actually it would be more like:
```purescript
forall a b. Ref a -> Ref b -> Boolean
```

ala https://hackage.haskell.org/package/base-4.8.1.0/docs/System-Mem-StableName.html

**Comment by rightfold** [comment]
Reference equality would be perfectly safe.

**Comment by rightfold** [comment]
Any new thoughts on this?

**Comment by garyb** [comment]
Referential equality is available through `purescript-unsafe-reference` - I think that probably solves this? An `Eq` instance still seems pretty suspect to me.
