### ISSUE TITLE
Is `newRef` actually effectful?

### ISSUE THREAD

**Issue by garyb** [purescript/purescript-refs#6]
I've bumped into a few cases where it would be _really_ handy to be able to construct a `Ref` outside of `Eff` - it seems to me that reading and writing a ref are definitely effectful, but creating one isn't necessarily so. Thoughts?

**Comment by paf31** [comment]
I think you might be able to write `unsafeCoerce` this way, but I'm not sure. Here is an example where all three are considered pure: https://github.com/paf31/purescript-benign/blob/master/test/Main.purs#L8-L15

but I think the same issue applies if you define the `Ref` at the top level.

**Comment by garyb** [comment]
Bah!
