### ISSUE TITLE
Return value from writeRef and modifyRef

### ISSUE THREAD

**Issue by texastoland** [purescript/purescript-refs#9]
Preempted by purescript/purescript-st#4:

``` purs
modifySTRef :: forall a h r. STRef h a -> (a -> a) -> Eff (st :: ST h | r) a
modifyRef   :: forall s   r.   Ref   s -> (s -> s) -> Eff (ref :: REF | r) Unit
```

In particular the current behavior of `modifyRef'` strangely returns an arbitrary value not what's stored.

**Comment by paf31** [comment]
> strangely returns an arbitrary value not what's stored

Why is this strange?

**Comment by texastoland** [comment]
Because the value returned doesn't necessarily correlate to the value passed? Can't that be accomplished with `map` instead of an extra argument? I assumed it wasn't implemented in `ST` for that reason?

**Comment by paf31** [comment]
But you've lost the ability to have the return value depend on the _original_ value too.

**Comment by texastoland** [comment]
I don't understand why that'd be desirable. I still have the value passed in. If I want it inside the Monad that sounds like `liftEff` or just extract the new value, combine it with the original, and `pure`. If there were a practical use case it wouldn't need FFI and should be added to `ST`.

**Comment by texastoland** [comment]
Is there an example I can try? Its the shape of the function that looks out of place and could be achieved with combinations of functions.

**Comment by paf31** [comment]
How can you accomplish the equivalent of

```purescript
increment <- modifyRef' ref \old -> { state: new, value: new - old }
```

**Comment by texastoland** [comment]
```purs
main = do
  ref <- newRef 10
  diff <- dec' ref 100
  logShow diff -- 100 - 10 = 90
  diff <- dec ref 1000
  logShow diff -- 1000 - 100 = 900

dec ref new = do
  old <- readRef ref
  writeRef ref new
  pure (new - old)

dec' ref new = modifyRef' ref \old ->
  { state: new
  , value: new - old
  }
```

Is there a common problem that needs read/write in a single call? Could it at least be named better? I struggled through the example remembering what `state` and `value` mean. Should it not be added to `ST`?

**Comment by paf31** [comment]
Right, but you've basically implemented `modifyRef'` there. It's just a question of which one you consider more basic. Since they can both be implemented in terms of one another, I don't think there's a good reason to prefer one or the other. The current way is compatible with the Haskell `IORef` library.

**Comment by texastoland** [comment]
Since the FFI is simpler the other way around could I switch which implements it and add it to `ST`?

**Comment by paf31** [comment]
`atomicModifyIORef` is an atomic operation in the sense of atomic updates.

I suspect this way round is faster, so I'd like to measure both before changing. What's the reason for changing?

**Comment by texastoland** [comment]
Because I'm working on `ST` and it was different.

**Comment by texastoland** [comment]
Discussed offline with the following conclusions:

1. `modifyRef'` should remain named as is and added to `ST`.
2. The record returned should have the shape `{ newValue, returnValue }` for clarity.
3. Since either can be implemented in terms of the other let's give the more common use case less indirection.

I'm pasting my implementation of `modifyRef'` and generated code (with ES6 arrows for legibility) for discussion:

```purs
main = do
  ref <- newRef "Hello"
  let newValue = "World"
  greeting <- modifyRef' ref (\val -> { newValue, returnValue: val <> " " <> newValue })
  log greeting

modifyRef' ref f = do
  value <- readRef ref
  let t = f value
  writeRef ref t.newValue
  pure t.returnValue
```

```js
var main = () => {
  var v = Control_Monad_Eff_Ref.newRef("Hello")();
  var v1 = modifyRef$prime(v)(val => ({
    newValue: "World", 
    returnValue: val + (" " + "World")
  }))();
  return Control_Monad_Eff_Console.log(v1)();
};

var modifyRef$prime = ref => f => () => {
  var v = Control_Monad_Eff_Ref.readRef(ref)(); -- calls FFI
  var t = f(v);
  Control_Monad_Eff_Ref.writeRef(ref)(t.newValue)(); -- calls FFI
  return t.returnValue;
};
```

**Comment by texastoland** [comment]
Hmm my implementation incurs a dependency on `bind` and `pure`. Switching back.
